export type Kpi = { label: string; value: string; subtext: string };
export type BarStat = { label: string; value: number; ratio: number; valueText: string };
export type AlertMatch = {
  id: number;
  callId: number;
  ruleName: string;
  detail: string;
  matchedAt: number;
  isImported: boolean;
  notificationSuppressed: boolean;
  dismissedAtUtc: string;
  active: boolean;
  systemShortName: string;
  talkgroup: number;
  talkgroupName: string;
  category: string;
  transcription: string;
  transcriptionStatus: string;
  qualityReason: string;
  audioUrl: string;
};
export type Incident = {
  id: number;
  incidentKey: string;
  title: string;
  detail: string;
  category: string;
  status: string;
  firstSeen: number;
  lastSeen: number;
  confidence: number;
  calls: { callId: number; rawTimestamp: number; transcript: string; audioUrl: string; category: string; talkgroupName: string; systemShortName: string; talkgroup: number; hasAlertMatch?: boolean; hasActiveAlert?: boolean; alertRules?: string }[];
};
export type CategoryInsight = {
  id: number;
  title: string;
  detail: string;
  firstSeen: number;
  lastSeen: number;
  score: number;
  callCount: number;
  calls: { callId: number; rawTimestamp: number; transcript: string; audioUrl: string; category: string }[];
};
export type TopTalkgroup = {
  label: string;
  talkgroupKey: string;
  systemShortName: string;
  talkgroup: number;
  count: number;
  share: number;
  lastHeard: number;
  trend: number[];
  trendCounts: number[];
  trendLabels: string[];
  trendStartLabel: string;
  trendBucketLabel: string;
  trendEndLabel: string;
};
export type HourCategory = { hour: number; category: string; count: number };
export type LocationHeat = {
  areaId: string;
  areaLabel: string;
  systemShortName: string;
  locationText: string;
  geocodeQuery: string;
  geocodeDisplayName: string;
  geocodeProvider: string;
  geocodePrecision: string;
  geocodeConfidence: number;
  latitude: number;
  longitude: number;
  count: number;
  intensity: number;
  lastHeard: number;
  category: string;
  callIds: number[];
  incidentTitles: string[];
  incidentLinks: { incidentId: number; title: string }[];
  sourceCalls: { callId: number; rawTimestamp: number; category: string; talkgroupName: string; transcript: string; audioUrl: string }[];
};
export type QualityHour = { hour: number; empty: number; failure: number; inaudible: number; short: number };
export type Dashboard = {
  kpis: Kpi[];
  volumeByHourCategory: HourCategory[];
  locationHeat: LocationHeat[];
  qualityByHour: QualityHour[];
  inaudibleBySystem: BarStat[];
  problemTalkgroups: BarStat[];
  categoryShare: BarStat[];
  topTalkgroups: TopTalkgroup[];
  alerts: AlertMatch[];
  incidents: Incident[];
  tokenUsage: TokenUsageSummary;
};
export type StatusSummary = { calls: number; incidents: number; hiddenIncidents?: number; alerts: number; tokens: number };
export type EngineCall = {
  id: number;
  startTime: number;
  stopTime: number;
  systemShortName: string;
  talkgroup: number;
  talkgroupName: string;
  category: string;
  audioPath: string;
  transcription: string;
  transcriptionStatus: string;
  qualityReason: string;
  isImported: boolean;
  isAlertMatch: boolean;
};
export type CategoryPage = {
  category: string;
  groupBy: string;
  groups: { label: string; calls: EngineCall[]; talkgroupKey: string; systemShortName: string; talkgroup: number; count: number; lastHeard: number; strongCount: number; weakCount: number }[];
  insights: CategoryInsight[];
  incidents: Incident[];
};
export type Job = {
  id: number;
  type: string;
  status: string;
  total: number;
  completed: number;
  failed: number;
  message: string;
  createdAtUtc: string;
  startedAtUtc?: string | null;
  finishedAtUtc?: string | null;
};
export type JobLog = { id: number; jobId: number; timestampUtc: string; stream: string; text: string };
export type SetupArtifact = { path: string; exists: boolean; notes: string };
export type SetupArtifactReport = { hasBlockingArtifacts: boolean; artifacts: SetupArtifact[]; manualCommands: string[] };
export type SetupSdrDevice = {
  index: number;
  type: string;
  serial: string;
  label: string;
  driver: string;
  deviceArgs: string;
  usbLine: string;
  sampleRateOptions: number[];
  defaultSampleRate: number;
  gainMode: string;
  defaultGain: string;
  warning: string;
};
export type SetupSdrDetection = { devices: SetupSdrDevice[]; rawOutput: string; message: string };
export type EngineHealth = {
  status: string;
  version: string;
  stackName: string;
  databasePath: string;
  audioRoot: string;
  queueDepth: number;
  liveQueueDepth: number;
  priorityLiveQueueDepth: number;
  backlogQueueDepth: number;
  queueUnderPressure: boolean;
  queuePressureThreshold: number;
  pendingTranscriptions: number;
  liveTranscriptionWorkers: number;
  whisperThreadsPerWorker: number;
  throughputWindowMinutes: number;
  recentCallsIngested: number;
  recentCallsTranscribed: number;
  recentIngestPerMinute: number;
  recentTranscribedPerMinute: number;
  recentAudioSecondsIngested: number;
  recentAudioSecondsTranscribed: number;
  recentAudioSecondsIngestedPerMinute: number;
  recentAudioSecondsTranscribedPerMinute: number;
  pendingAudioSeconds: number;
  recentTranscriptionSamples: number;
  averageTranscriptionSeconds: number;
  averageAudioSeconds: number;
  averageTranscriptionRealtimeFactor: number;
  ingest: {
    paused: boolean;
    untilQueueClear: boolean;
    reason: string;
    pausedAtUtc?: string | null;
    droppedCalls: number;
    droppedCallsThisPause: number;
  };
  liveTrActivity?: {
    status: string;
    stale: boolean;
    thresholdSeconds: number;
    ageSeconds: number;
    lastActivityUtc?: string | null;
    lastLiveCallUtc?: string | null;
    lastTrHealthUtc?: string | null;
    startedAtUtc: string;
    message: string;
  };
  aiWorkBlockedReason?: string | null;
  aiCompletionHealth: AiCompletionHealth;
  embeddingHealth: EmbeddingPipelineHealth;
  workBlockedReason?: string | null;
  serverTimeUtc: string;
};
export type AiCompletionHealth = {
  status: string;
  message: string;
  windowMinutes: number;
  requests: number;
  failures: number;
  timeoutFailures: number;
  noValidResultFailures: number;
  consecutiveFailures: number;
  latestFailureUtc?: string | null;
  latestFailureKind: string;
  latestFailure: string;
};
export type EmbeddingPipelineHealth = {
  enabled: boolean;
  qdrantOk: boolean;
  embeddingEndpointOk: boolean;
  status: string;
  collection: string;
  model: string;
  vectorSize: number;
  queueDepth: number;
  embeddedCalls: number;
  failedCalls: number;
  pendingCalls: number;
  oldestPendingUtc?: string | null;
  lastSearchMs: number;
  lastUpsertMs: number;
  lastError: string;
};
export type QueueSnapshot = {
  queueDepth: number;
  liveQueueDepth: number;
  priorityLiveQueueDepth: number;
  backlogQueueDepth: number;
  queueUnderPressure: boolean;
  queuePressureThreshold: number;
  pendingTranscriptions: number;
  liveTranscriptionWorkers: number;
  whisperThreadsPerWorker: number;
  throughputWindowMinutes: number;
  recentCallsIngested: number;
  recentCallsTranscribed: number;
  recentIngestPerMinute: number;
  recentTranscribedPerMinute: number;
  recentAudioSecondsIngested: number;
  recentAudioSecondsTranscribed: number;
  recentAudioSecondsIngestedPerMinute: number;
  recentAudioSecondsTranscribedPerMinute: number;
  pendingAudioSeconds: number;
  recentTranscriptionSamples: number;
  averageTranscriptionSeconds: number;
  averageAudioSeconds: number;
  averageTranscriptionRealtimeFactor: number;
  ingest: EngineHealth["ingest"];
  aiWorkBlockedReason?: string | null;
  aiCompletionHealth: AiCompletionHealth;
  embeddingHealth: EmbeddingPipelineHealth;
  pendingCalls: {
    callId: number;
    startTime: number;
    systemShortName: string;
    talkgroup: number;
    talkgroupName: string;
    category: string;
    isImported: boolean;
    audioPath: string;
  }[];
  topAudioTalkgroups: QueueTalkgroupLoad[];
};
export type SystemCpuSnapshot = {
  generatedAtUtc: string;
  windowMinutes: number;
  processorCount: number;
  latest?: SystemCpuSample | null;
  peaks: SystemCpuSample;
  severity: "ok" | "warning" | "error" | string;
  summary: string;
  insights: SystemCpuInsight[];
};
export type SystemCpuSample = {
  windowEndUtc?: string | null;
  trCpuPercent: number;
  trCpuHostPercent: number;
  trRssMb: number;
  trThreadCount: number;
  hostTempC: number;
  hostLoad1: number;
  hostLoadHostPercent: number;
  hostThrottledFlags: string;
};
export type SystemCpuInsight = {
  label: string;
  value: string;
  status: "ok" | "warning" | "error" | string;
  detail: string;
};
export type QueueTalkgroupLoad = {
  systemShortName: string;
  talkgroup: number;
  talkgroupName: string;
  category: string;
  calls: number;
  audioSeconds: number;
  averageAudioSeconds: number;
  pendingCalls: number;
  pendingAudioSeconds: number;
};
export type SystemRecommendation = {
  id: string;
  section: string;
  severity: "high" | "medium" | "low" | string;
  title: string;
  detail: string;
  action: string;
  target: { topTab: string; subTab: string; anchor: string };
  actions: { kind: string; label: string; description: string; talkgroups?: number[] | null }[];
  baseline?: {
    firstSeenUtc: string;
    lastSeenUtc: string;
    baselineValue: string;
    activeObservations: number;
    ageHours: number;
    priorityDemoted: boolean;
    originalSeverity: string;
  } | null;
  runbook?: {
    title: string;
    goal: string;
    evidence: string[];
    steps: { title: string; detail: string; target: { topTab: string; subTab: string; anchor: string } }[];
    caveat: string;
    diagnostics: {
      label: string;
      value: string;
      status: string;
      detail: string;
    }[];
    talkgroupCandidates: {
      systemShortName: string;
      talkgroup: number;
      talkgroupName: string;
      category: string;
      calls: number;
      audioSeconds: number;
      averageAudioSeconds: number;
      pendingCalls: number;
      pendingAudioSeconds: number;
      alreadyDeferred: boolean;
      reason: string;
    }[];
  } | null;
};
export type SystemRecommendations = {
  openCount: number;
  highCount: number;
  mediumCount: number;
  lowCount: number;
  items: SystemRecommendation[];
  ignoredItems: SystemRecommendation[];
};
export type TrHealth = {
  id: number;
  windowStartUtc: string;
  windowEndUtc: string;
  scope: string;
  decodeLines: number;
  decodeZero: number;
  decodeZeroPct: number;
  decodeRateTotal: number;
  ccSummaryDecodeLines: number;
  ccSummaryDecodeZero: number;
  ccSummaryDecodeRateTotal: number;
  ccSummaryAvgDecodeRate: number;
  ccSummaryDecodeZeroPct: number;
  lowDecodeWarningLines: number;
  lowDecodeWarningZero: number;
  lowDecodeWarningRateTotal: number;
  lowDecodeWarningAvgRate: number;
  lowDecodeWarningZeroPct: number;
  retunes: number;
  callsStarted: number;
  callsConcluded: number;
  updateNotGrant: number;
  noTxRecorded: number;
  recorderExhausted: number;
  sampleStops: number;
  unableSource: number;
  tuningErrSamples: number;
  tuningErrTotalAbsHz: number;
  tuningErrMaxAbsHz: number;
};
export type TrHealthMetric = { metric: string; value: string; notes: string; isIssue: boolean };
export type TrSourceCoverage = {
  index: number;
  device: string;
  centerMhz: number;
  lowMhz: number;
  highMhz: number;
  digitalRecorders: number;
  firstMatchCalls: number;
  coverableCalls: number;
  uniqueFrequencies: number;
  notes: string;
  isIssue: boolean;
};
export type TrSourcePlan = {
  systemShortName: string;
  lowMhz: number;
  highMhz: number;
  recommendedCenterMhz: number;
  assignedSourceIndex?: number | null;
  assignedDevice: string;
  notes: string;
  isIssue: boolean;
};
export type TrHealthSeries = { label: string; values: number[]; isBaseline: boolean };
export type TrHealthChart = { title: string; yAxisLabel: string; valueFormat: string; labels: string[]; series: TrHealthSeries[]; baselineNote: string };
export type TrHealthSummary = {
  title: string;
  window: string;
  lastWindow: string;
  source: string;
  summaryText: string;
  metrics: TrHealthMetric[];
  systems: TrHealthMetric[];
  sourceCoverage: TrSourceCoverage[];
  sourcePlan: TrSourcePlan[];
  remedies: TrHealthMetric[];
  charts: TrHealthChart[];
  samples: TrHealth[];
};
export type TrRfAnalysis = {
  system: string;
  start: number;
  end: number;
  window: string;
  hasEnoughPostChangeData: boolean;
  summary: string;
  metrics: TrHealthMetric[];
  comparison: TrHealthMetric[];
  retuneTargets: TrHealthMetric[];
  recommendations: TrHealthMetric[];
};
export type QualityAuditGroup = {
  label: string;
  totalCalls: number;
  problemCalls: number;
  inaudibleCalls: number;
  problemPercent: number;
  inaudiblePercent: number;
};
export type QualityAuditHour = { hour: number; totalCalls: number; problemCalls: number; inaudibleCalls: number };
export type QualityAuditSample = {
  callId: number;
  startTime: number;
  systemShortName: string;
  source: number;
  talkgroup: number;
  talkgroupName: string;
  category: string;
  durationSeconds: number;
  transcriptionStatus: string;
  qualityReason: string;
  transcription: string;
  audioUrl: string;
};
export type QualityAudit = {
  totalCalls: number;
  problemCalls: number;
  inaudibleCalls: number;
  problemPercent: number;
  inaudiblePercent: number;
  byReason: QualityAuditGroup[];
  bySystem: QualityAuditGroup[];
  byTalkgroup: QualityAuditGroup[];
  byHour: QualityAuditHour[];
  samples: QualityAuditSample[];
};
export type TrTroubleshoot = {
  health: TrHealthSummary;
  qualityAudit: QualityAudit;
  config: any;
  logOutput: string;
  diagnostics: string;
  insightsText: string;
};
export type TokenUsageSummary = { requests: number; successes: number; failures: number; truncated: number; canceled: number; httpOrOtherErrors: number; promptTokens: number; completionTokens: number; totalTokens: number; estimatedStandardCost: number; timeoutFailures: number; noValidResultFailures: number };
export type TokenUsageBucket = { label: string; totalTokens: number; promptTokens: number; completionTokens: number; requests: number };
export type TokenUsageFailureBreakdown = { kind: string; requests: number; promptTokens: number; completionTokens: number; totalTokens: number; latestUtc: string; example: string };
export type TokenUsageEntry = { id: number; timestampUtc: string; triggerActivity: string; requestKind: string; success: boolean; error: string; endpoint: string; requestModel: string; responseModel: string; finishReason: string; inputChars: number; payloadChars: number; promptTokens: number; completionTokens: number; totalTokens: number };
export type TokenUsageReport = { ledger: string; summary: TokenUsageSummary; monthlySummary: TokenUsageSummary; allTimeSummary: TokenUsageSummary; failuresByKind: TokenUsageFailureBreakdown[]; byDay: TokenUsageBucket[]; byTrigger: TokenUsageBucket[]; entries: TokenUsageEntry[] };
export type RemoteBandwidthSummary = { requestBytes: number; responseBytes: number; totalBytes: number; requests: number; missingAudioFiles: number };
export type RemoteBandwidthBucket = { label: string; activity: string; requestBytes: number; responseBytes: number; totalBytes: number; requests: number };
export type RemoteBandwidthEntry = { timestampUtc: string; activity: string; endpoint: string; requestBytes: number; responseBytes: number; totalBytes: number; basis: string; estimated: boolean };
export type RemoteBandwidthReport = { ledger: string; remoteHost: string; transcriptionEndpoint: string; aiEndpoint: string; transcriptionIncluded: boolean; notes: string; summary: RemoteBandwidthSummary; monthlySummary: RemoteBandwidthSummary; allTimeSummary: RemoteBandwidthSummary; byDay: RemoteBandwidthBucket[]; byActivity: RemoteBandwidthBucket[]; entries: RemoteBandwidthEntry[] };
export type IncidentOperationAuditRow = { id: number; timestampUtc: string; systemShortName: string; incidentKey: string; operation: string; accepted: boolean; reason: string; score: number; callIds: number[]; metadataJson: string };
export type ProfileTalkgroupSetting = { key?: string; systemShortName?: string; id: number; enabled?: boolean | null; label?: string; category?: string; incidentEligible?: boolean | null };
export type ProcessingProfile = { id: string; name: string; includePolice: boolean; includeFire: boolean; includeEMS: boolean; includeTraffic: boolean; includeOther: boolean; allowedTalkgroups: number[]; talkgroups?: ProfileTalkgroupSetting[]; createdAtUtc?: string; updatedAtUtc?: string };
export type ProfileState = { activeProfileId: string; profiles: ProcessingProfile[]; restartRecommended?: boolean; generatedCsvPath?: string; message?: string };
export type TalkgroupOption = { talkgroup: number; label: string; category: string };
export type TalkgroupCatalogItem = {
  key: string;
  systemShortName: string;
  id: number;
  mode: string;
  alphaTag: string;
  description: string;
  tag: string;
  sourceCategory: string;
  opsCategory: string;
  enabled: boolean;
  incidentEligible: boolean;
  source: string;
  notes: string;
  updatedAtUtc?: string;
};
export type TalkgroupCatalogDocument = { schemaVersion: number; updatedAtUtc?: string; items: TalkgroupCatalogItem[] };
export type TalkgroupCatalogResponse = {
  catalogPath: string;
  generatedCsvPath: string;
  activeProfileId?: string;
  trRestartRecommended: boolean;
  warning: string;
  document: TalkgroupCatalogDocument;
  effectiveItems?: TalkgroupCatalogItem[];
};
export type TalkgroupCatalogSaveResult = { count: number; backupPath?: string | null; generatedCsvPath: string; generatedCsvBackupPath?: string | null; trRestartRecommended: boolean };
export type TalkgroupTrCsvResult = { path: string; backupPath?: string | null; enabledCount: number };
export type SetupCheck = { id: string; label: string; required: boolean; ok: boolean; message: string };
export type SetupStatus = {
  completed: boolean;
  currentStep: string;
  checks: SetupCheck[];
  detection: any;
  values: any;
};
export type BackupArchive = { name: string; path: string; bytes: number; createdUtc: string; modifiedUtc: string };
export type BackupManifestEntry = { kind: string; path: string; archivePath: string; bytes: number; sha256: string };
export type BackupManifest = {
  manifestVersion: number;
  product: string;
  createdUtc: string;
  hostname: string;
  stackName: string;
  pizzadConfigPath: string;
  databasePath: string;
  audioRoot: string;
  appDataRoot: string;
  trConfigPath: string;
  trTalkgroupsPath: string;
  qdrantStoragePath: string;
  audioStartUtc?: string | null;
  audioEndUtc?: string | null;
  entries: BackupManifestEntry[];
  warnings: string[];
};
export type BackupEstimateKind = { kind: string; bytes: number; fileCount: number };
export type BackupEstimate = { bytes: number; fileCount: number; kinds: BackupEstimateKind[]; warnings: string[] };
export type BackupCreateResult = { name: string; path: string; bytes: number; fileCount: number; warnings: string[] };
export type BackupRestoreCheck = { name: string; ok: boolean; message: string };
export type BackupRestorePreview = { stagePath: string; manifest: BackupManifest; checks: BackupRestoreCheck[] };
export type BackupRestoreApplyResult = { scheduled: boolean; message: string };
export type BackupRestoreCancelResult = { canceled: boolean; message: string };
export type MigrationActionResult = { ok: boolean; message: string };
export type MigrationResetResult = { ok: boolean; message: string; warnings: string[]; backup?: BackupCreateResult | null };
export type SetupValidationResult = { ok: boolean; message: string; detail?: any };
export type SetupTalkgroupRow = { key: string; systemShortName: string; id: number; mode: string; alphaTag: string; description: string; tag: string; category: string; opsCategory: string; included: boolean; exclusionReason: string };
export type SetupTalkgroupPreview = { rows: SetupTalkgroupRow[]; includedByCategory: Record<string, number>; includedCount: number; excludedCount: number; diagnostics: string };
export type SetupTrConfigSystem = { systemName: string; shortName: string; siteName: string; frequenciesMhz: number[]; controlChannelsMhz: number[]; centerFrequency: number; assignedSerial: string; warning: string };
export type SetupTrConfigSource = { label: string; serial: string; type: string; driver: string; deviceArgs: string; centerFrequency: number; sampleRate: number; gain: string; gainMode: string; coveredFrequenciesMhz: number[]; omittedFrequenciesMhz: number[] };
export type SetupTrConfigDraft = { configJson: string; systems: SetupTrConfigSystem[]; sources: SetupTrConfigSource[]; warnings: string[]; diagnostics: string };
export type SetupTrConfigSite = { name: string; shortName: string; frequencyCount: number; controlChannelCount: number; controlChannelsMhz: number[] };
export type SetupTrConfigSites = { systemName: string; sites: SetupTrConfigSite[]; diagnostics: string };
export type SetupTrConfigSourcePlan = { systemName: string; systems: SetupTrConfigSystem[]; sources: SetupTrConfigSource[]; requiredSourceCount: number; availableSourceCount: number; warnings: string[]; diagnostics: string };
export type SetupAreaBoundaryCandidate = { label: string; kind: string; source: string; geoId: string; north: number; south: number; east: number; west: number };
export type SetupAreaBoundaryResponse = { query: string; candidates: SetupAreaBoundaryCandidate[]; diagnostics: string };
export type TrConfigEditorSource = { index: number; device: string; serial: string; centerFrequency: number; sampleRate: number; error: number; gain: string };
export type TrConfigEditorSystem = { shortName: string; type: string; modulation: string; controlChannelsHz: number[]; voiceFrequenciesHz: number[]; talkgroupsFile: string };
export type TrConfigEditorSummary = { systems: TrConfigEditorSystem[]; sources: TrConfigEditorSource[]; warnings: string[] };
export type TrConfigEditor = { livePath: string; draftPath: string; configJson: string; liveConfigJson: string; hasDraft: boolean; parseOk: boolean; parseMessage: string; summary: TrConfigEditorSummary };
export type TrConfigEditorApplyResult = { ok: boolean; message: string; save: SetupValidationResult; restartJob?: Job | null; editor: TrConfigEditor };
export type TrConfigBackup = { name: string; path: string; bytes: number; createdAtUtc: string };
export type TrConfigRestoreResult = { ok: boolean; message: string; backupPath: string; restoreBackupPath: string; serviceOutput: string };
export type SetupCalibrationRange = { lowHz: number; highHz: number; centerHz: number };
export type SetupCalibrationSystemPlan = { shortName: string; modulation: string; controlChannelsHz: number[]; voiceFrequenciesHz: number[]; requiredRanges: SetupCalibrationRange[]; requiredSdrCount: number; proposedSourceIndexes: number[]; warnings: string[] };
export type SetupCalibrationSourcePlan = { index: number; serial: string; device: string; centerFrequency: number; sampleRate: number; errorHz: number; gain: string; coveredSystems: string[] };
export type SetupCalibrationPlan = { systems: SetupCalibrationSystemPlan[]; sources: SetupCalibrationSourcePlan[]; warnings: string[]; diagnostics: string };
export type SiteSetupAppliedSource = { index: number; device: string; serial: string; centerHz: number; sampleRate: number; errorHz: number; gain: string };
export type SiteSetupAppliedConfig = { configPath: string; configExists: boolean; configHash: string; configUpdatedAtUtc?: string | null; systemShortNames: string[]; controlChannelsHz: number[]; sources: SiteSetupAppliedSource[] };
export type SiteSetupStatus = { monitoringState: string; message: string; pendingApply: boolean; desiredVersion: number; appliedConfigHash: string; lastAppliedAtUtc?: string | null };
export type SiteSetupPendingChange = { category: string; summary: string };
export type SiteSetupActivity = { id: number; timestampUtc: string; category: string; action: string; summary: string; detailsJson: string; desiredVersion: number; appliedConfigHash: string; monitoringState: string; source: string };
export type SiteSetupRfSelection = { frequencyHz: number; sourceIndex?: number | null; gain: string; sampleRateHz?: number | null; errorHz?: number | null; snrDb?: number | null; confidence?: number | null };
export type SiteSetupConfig = {
  desiredVersion: number;
  siteLabel: string;
  locationNotes: string;
  radioReferenceSid: string;
  systemShortNames: string[];
  sourcePlanSystemShortNames: string[];
  sourcePlanMode: string;
  systems: RfSurveySystem[];
  selectedSourceIndexes: number[];
  sources: RfSurveySource[];
  rfSelections: SiteSetupRfSelection[];
  rfPath: RfSurveyPathProfile;
  updatedAtUtc?: string | null;
  lastAppliedAtUtc?: string | null;
  lastAppliedConfigHash: string;
};
export type SiteSetup = { desired: SiteSetupConfig; applied: SiteSetupAppliedConfig; status: SiteSetupStatus; pendingChanges: SiteSetupPendingChange[]; recentActivity: SiteSetupActivity[] };
export type RfSurveyRfChainItem = {
  type: string;
  label: string;
  connectorIn: string;
  connectorOut: string;
  length: string;
  loss: string;
  power: string;
  notes: string;
  connectorInType?: string;
  connectorInGender?: string;
  connectorOutType?: string;
  connectorOutGender?: string;
  gainDb?: string;
  groundPlane?: string;
  portCount?: string;
  powerPass?: string;
  powerMethod?: string;
  passband?: string;
};
export type RfSurveyPathProfile = {
  antenna: string;
  antennaType: string;
  antennaMount: string;
  antennaPolarization: string;
  aimedAtSite: string;
  positionNotes: string;
  connectorChain: string;
  coax: string;
  splitterOrMulticoupler: string;
  lna: string;
  filters: string;
  sdrNotes: string;
  observations: string;
  chain: RfSurveyRfChainItem[];
};
export type RfSurveySource = { index: number; device: string; serial: string; sdrType: string; centerHz: number; sampleRate: number; errorHz: number; gain: string };
export type RfSurveyDevice = { index: number; serial: string; label: string; sdrType: string; usbLine: string; warning: string; sampleRateOptions?: number[]; defaultSampleRate?: number };
export type RfSurveySystem = { shortName: string; siteLabel: string; controlChannelsHz: number[]; voiceFrequenciesHz: number[]; radioReferenceSid?: string; talkgroupSystemShortName?: string };
export type RfSurveyProfile = {
  siteLabel: string;
  radioReferenceSid?: string;
  systemShortName: string;
  systemShortNames: string[];
  sourcePlanSystemShortNames: string[];
  sourcePlanMode: string;
  systems: RfSurveySystem[];
  mode: string;
  groundTruthSource: string;
  controlChannelsHz: number[];
  voiceFrequenciesHz: number[];
  sources: RfSurveySource[];
  devices: RfSurveyDevice[];
  sourceOverride: boolean;
  selectedSourceIndexes: number[];
  rfPath: RfSurveyPathProfile;
  currentStep: number;
  measurementMode: string;
  probeDurationSeconds: number;
  warnings: string[];
};
export type RfSurveySession = {
  id: string;
  status: string;
  mode: string;
  siteLabel: string;
  systemShortName: string;
  verdict: string;
  stability: string;
  sdrSummary: string;
  rfPathSummary: string;
  bestControlChannel: string;
  sourcePlanSummary: string;
  recommendationState: string;
  artifactPath: string;
  createdAtUtc: string;
  updatedAtUtc: string;
  completedAtUtc?: string | null;
};
export type RfSurveyToolStatus = { id: string; label: string; category: string; required: boolean; installed: boolean; version: string; command: string; purpose: string; installHint: string };
export type RfSurveyToolPrep = { generatedAtUtc: string; readyForGuidedSurvey: boolean; readyForControlChannelTests: boolean; readyForVoiceCapture: boolean; readyForTranscriptionGate: boolean; tools: RfSurveyToolStatus[]; warnings: string[] };
export type RfSurveyExperiment = { id: string; type: string; status: string; hypothesis: string; requiredSetup: string; resultSummary: string; blockingIssue: string; evidenceJson: string; interpretationJson: string; createdAtUtc: string; startedAtUtc?: string | null; finishedAtUtc?: string | null };
export type RfSurveyExperimentPlan = { type: string; label: string; purpose: string; enabled: boolean; blockingIssue: string; requiredSetup: string };
export type RfSurveyCancelExperimentResult = { cancelRequested: boolean; message: string; cleanupOutput: string };
export type RfSurveySweepProgressRow = { sourceIndex: number; controlChannelHz: number; gain: string; status: string; issue: string; snrDb?: number | null; peakOffsetHz?: number | null; overload: boolean };
export type RfSurveySweepCandidateProgress = { id: string; sourceIndex: number; controlChannelHz: number; gain: string; errorHz: number; p25Status: string; p25Summary: string; metricsStatus: string; metricsSummary: string; voiceStatus: string; voiceSummary: string; voiceTotalCalls: number; voiceRealCalls: number };
export type RfSurveySweepProgress = { active: boolean; directory: string; rows: RfSurveySweepProgressRow[]; candidates?: RfSurveySweepCandidateProgress[] | null };
export type RfSurveyWaterfallFrame = { sequence: number; capturedAtUtc: string; centerHz: number; sampleRate: number; startHz: number; binWidthHz: number; powersDb: number[]; minDb: number; maxDb: number; noiseFloorDb: number; peakDb: number; peakFrequencyHz: number; clipPct: number; overload: boolean; bytes: number; output: string };
export type RfSurveyWaterfallStatus = { active: boolean; status: string; message: string; sourceIndex: number; sdrType: string; centerHz: number; sampleRate: number; gain: string; binCount: number; startedAtUtc: string | null; updatedAtUtc: string | null; frame: RfSurveyWaterfallFrame | null; trWasActive: boolean; trStopOutput: string; trRestartOutput: string; trRestartError: string; frames?: RfSurveyWaterfallFrame[] | null };
export type RfSurveyP25ProbePreview = { configured: boolean; ready: boolean; command: string; workingDirectory: string; blockingIssue: string; placeholders: string[] };
export type RfSurveyExportPlan = { surveyId: string; artifactPath: string; planPath: string; markdownPath: string; verdict: string; stability: string; recommendations: string[]; blockers: string[] };
export type RfSurveyTrActionResult = { ok: boolean; action: string; message: string; candidatePath: string; backupPath: string; restorePath: string; serviceOutput: string };
export type RfSurveyCandidate = { trialType: string; candidatePath: string; diffPath: string; summary: string; diffLines: string[]; warnings: string[] };
export type RfSurveyConfigDraft = { livePath: string; draftPath: string; configJson: string; liveConfigJson: string; summary: { selectedSourceIndexes: number[]; changes: string[]; warnings: string[]; draftPath: string } };
export type RfSurveyCaptureTrialResult = { apply: RfSurveyTrActionResult; voiceCapture: RfSurveyExperiment; restore?: RfSurveyTrActionResult | null; waitedSeconds: number };
export type RfSurveyNote = { text: string; createdAtUtc: string };
export type RfSurveyDetail = { session: RfSurveySession; profile: RfSurveyProfile; experiments: RfSurveyExperiment[]; notes: RfSurveyNote[]; toolPrep?: RfSurveyToolPrep | null; nextExperiments: RfSurveyExperimentPlan[] };
export type RfSurveyList = { sessions: RfSurveySession[]; artifactRoot: string };
