export type Kpi = { label: string; value: string; subtext: string };
export type BarStat = { label: string; value: number; ratio: number; valueText: string };
export type AlertMatch = {
  id: number;
  callId: number;
  ruleName: string;
  detail: string;
  matchedAt: number;
  isImported: boolean;
  notificationSuppressed: boolean;
  systemShortName: string;
  talkgroup: number;
  talkgroupName: string;
  category: string;
  transcription: string;
  transcriptionStatus: string;
  qualityReason: string;
  audioUrl: string;
};
export type Incident = {
  id: number;
  incidentKey: string;
  title: string;
  detail: string;
  category: string;
  status: string;
  firstSeen: number;
  lastSeen: number;
  confidence: number;
  calls: { callId: number; rawTimestamp: number; transcript: string; audioUrl: string; category: string }[];
};
export type CategoryInsight = {
  id: number;
  title: string;
  detail: string;
  firstSeen: number;
  lastSeen: number;
  score: number;
  callCount: number;
  calls: { callId: number; rawTimestamp: number; transcript: string; audioUrl: string; category: string }[];
};
export type TopTalkgroup = {
  label: string;
  talkgroup: number;
  count: number;
  share: number;
  lastHeard: number;
  trend: number[];
  trendCounts: number[];
  trendLabels: string[];
  trendStartLabel: string;
  trendBucketLabel: string;
  trendEndLabel: string;
};
export type HourCategory = { hour: number; category: string; count: number };
export type LocationHeat = {
  areaId: string;
  areaLabel: string;
  systemShortName: string;
  locationText: string;
  geocodeQuery: string;
  geocodeDisplayName: string;
  geocodeProvider: string;
  geocodePrecision: string;
  geocodeConfidence: number;
  latitude: number;
  longitude: number;
  count: number;
  intensity: number;
  lastHeard: number;
  category: string;
  callIds: number[];
  incidentTitles: string[];
  incidentLinks: { incidentId: number; title: string }[];
  sourceCalls: { callId: number; rawTimestamp: number; category: string; talkgroupName: string; transcript: string; audioUrl: string }[];
};
export type QualityHour = { hour: number; empty: number; failure: number; inaudible: number; short: number };
export type Dashboard = {
  kpis: Kpi[];
  volumeByHourCategory: HourCategory[];
  locationHeat: LocationHeat[];
  qualityByHour: QualityHour[];
  inaudibleBySystem: BarStat[];
  problemTalkgroups: BarStat[];
  categoryShare: BarStat[];
  topTalkgroups: TopTalkgroup[];
  alerts: AlertMatch[];
  incidents: Incident[];
  tokenUsage: TokenUsageSummary;
};
export type StatusSummary = { calls: number; incidents: number; alerts: number; tokens: number };
export type EngineCall = {
  id: number;
  startTime: number;
  stopTime: number;
  systemShortName: string;
  talkgroup: number;
  talkgroupName: string;
  category: string;
  audioPath: string;
  transcription: string;
  transcriptionStatus: string;
  qualityReason: string;
  isImported: boolean;
  isAlertMatch: boolean;
};
export type CategoryPage = {
  category: string;
  groupBy: string;
  groups: { label: string; calls: EngineCall[] }[];
  insights: CategoryInsight[];
  incidents: Incident[];
};
export type Job = {
  id: number;
  type: string;
  status: string;
  total: number;
  completed: number;
  failed: number;
  message: string;
  createdAtUtc: string;
  startedAtUtc?: string | null;
  finishedAtUtc?: string | null;
};
export type JobLog = { id: number; jobId: number; timestampUtc: string; stream: string; text: string };
export type SetupArtifact = { path: string; exists: boolean; notes: string };
export type SetupArtifactReport = { hasBlockingArtifacts: boolean; artifacts: SetupArtifact[]; manualCommands: string[] };
export type SetupSdrDevice = { index: number; serial: string; label: string; usbLine: string; warning: string };
export type SetupSdrDetection = { devices: SetupSdrDevice[]; rawOutput: string; message: string };
export type EngineHealth = {
  status: string;
  version: string;
  stackName: string;
  databasePath: string;
  audioRoot: string;
  queueDepth: number;
  liveQueueDepth: number;
  priorityLiveQueueDepth: number;
  backlogQueueDepth: number;
  queueUnderPressure: boolean;
  queuePressureThreshold: number;
  pendingTranscriptions: number;
  liveTranscriptionWorkers: number;
  whisperThreadsPerWorker: number;
  throughputWindowMinutes: number;
  recentCallsIngested: number;
  recentCallsTranscribed: number;
  recentIngestPerMinute: number;
  recentTranscribedPerMinute: number;
  recentAudioSecondsIngested: number;
  recentAudioSecondsTranscribed: number;
  recentAudioSecondsIngestedPerMinute: number;
  recentAudioSecondsTranscribedPerMinute: number;
  pendingAudioSeconds: number;
  recentTranscriptionSamples: number;
  averageTranscriptionSeconds: number;
  averageAudioSeconds: number;
  averageTranscriptionRealtimeFactor: number;
  ingest: {
    paused: boolean;
    untilQueueClear: boolean;
    reason: string;
    pausedAtUtc?: string | null;
    droppedCalls: number;
    droppedCallsThisPause: number;
  };
  aiWorkBlockedReason?: string | null;
  importWorkBlockedReason?: string | null;
  workBlockedReason?: string | null;
  serverTimeUtc: string;
};
export type QueueSnapshot = {
  queueDepth: number;
  liveQueueDepth: number;
  priorityLiveQueueDepth: number;
  backlogQueueDepth: number;
  queueUnderPressure: boolean;
  queuePressureThreshold: number;
  pendingTranscriptions: number;
  liveTranscriptionWorkers: number;
  whisperThreadsPerWorker: number;
  throughputWindowMinutes: number;
  recentCallsIngested: number;
  recentCallsTranscribed: number;
  recentIngestPerMinute: number;
  recentTranscribedPerMinute: number;
  recentAudioSecondsIngested: number;
  recentAudioSecondsTranscribed: number;
  recentAudioSecondsIngestedPerMinute: number;
  recentAudioSecondsTranscribedPerMinute: number;
  pendingAudioSeconds: number;
  recentTranscriptionSamples: number;
  averageTranscriptionSeconds: number;
  averageAudioSeconds: number;
  averageTranscriptionRealtimeFactor: number;
  ingest: EngineHealth["ingest"];
  aiWorkBlockedReason?: string | null;
  importWorkBlockedReason?: string | null;
  pendingCalls: {
    callId: number;
    startTime: number;
    systemShortName: string;
    talkgroup: number;
    talkgroupName: string;
    category: string;
    isImported: boolean;
    audioPath: string;
  }[];
  topAudioTalkgroups: QueueTalkgroupLoad[];
};
export type QueueTalkgroupLoad = {
  systemShortName: string;
  talkgroup: number;
  talkgroupName: string;
  category: string;
  calls: number;
  audioSeconds: number;
  averageAudioSeconds: number;
  pendingCalls: number;
  pendingAudioSeconds: number;
};
export type SystemRecommendation = {
  id: string;
  section: string;
  severity: "high" | "medium" | "low" | string;
  title: string;
  detail: string;
  action: string;
  target: { topTab: string; subTab: string; anchor: string };
  actions: { kind: string; label: string; description: string; talkgroups?: number[] | null }[];
  runbook?: {
    title: string;
    goal: string;
    evidence: string[];
    steps: { title: string; detail: string; target: { topTab: string; subTab: string; anchor: string } }[];
    caveat: string;
    diagnostics: {
      label: string;
      value: string;
      status: string;
      detail: string;
    }[];
    talkgroupCandidates: {
      systemShortName: string;
      talkgroup: number;
      talkgroupName: string;
      category: string;
      calls: number;
      audioSeconds: number;
      averageAudioSeconds: number;
      pendingCalls: number;
      pendingAudioSeconds: number;
      alreadyDeferred: boolean;
      reason: string;
    }[];
  } | null;
};
export type SystemRecommendations = {
  openCount: number;
  highCount: number;
  mediumCount: number;
  lowCount: number;
  items: SystemRecommendation[];
};
export type TranscriptionBenchmarkRow = {
  callId: number;
  startTime: number;
  stopTime: number;
  audioSeconds: number;
  systemShortName: string;
  talkgroup: number;
  talkgroupName: string;
  category: string;
  totalSeconds: number;
  readSeconds: number;
  normalizeSeconds: number;
  whisperSeconds: number;
  qualitySeconds: number;
  scratchWriteSeconds: number;
  textLength: number;
  qualityReason: string;
  includeInSummaries: boolean;
  preview: string;
  error?: string | null;
};
export type TranscriptionBenchmarkResult = {
  startedAtUtc: string;
  provider: string;
  model: string;
  whisperThreads: number;
  sampleCount: number;
  lookbackHours: number;
  sampleSelectSeconds: number;
  modelInitSeconds: number;
  totalSeconds: number;
  processCpuSeconds: number;
  warmCallsPerMinute: number;
  averageTotalSeconds: number;
  averageAudioSeconds: number;
  averageRealtimeFactor: number;
  averageReadSeconds: number;
  averageNormalizeSeconds: number;
  averageWhisperSeconds: number;
  averageQualitySeconds: number;
  averageScratchWriteSeconds: number;
  whisperSharePercent: number;
  failureCount: number;
  rows: TranscriptionBenchmarkRow[];
};
export type TrHealth = {
  id: number;
  windowStartUtc: string;
  windowEndUtc: string;
  scope: string;
  decodeLines: number;
  decodeZero: number;
  decodeZeroPct: number;
  decodeRateTotal: number;
  ccSummaryDecodeLines: number;
  ccSummaryDecodeZero: number;
  ccSummaryDecodeRateTotal: number;
  ccSummaryAvgDecodeRate: number;
  ccSummaryDecodeZeroPct: number;
  lowDecodeWarningLines: number;
  lowDecodeWarningZero: number;
  lowDecodeWarningRateTotal: number;
  lowDecodeWarningAvgRate: number;
  lowDecodeWarningZeroPct: number;
  retunes: number;
  callsStarted: number;
  callsConcluded: number;
  updateNotGrant: number;
  noTxRecorded: number;
  recorderExhausted: number;
  sampleStops: number;
  unableSource: number;
  tuningErrSamples: number;
  tuningErrTotalAbsHz: number;
  tuningErrMaxAbsHz: number;
};
export type TrHealthMetric = { metric: string; value: string; notes: string; isIssue: boolean };
export type TrSourceCoverage = {
  index: number;
  device: string;
  centerMhz: number;
  lowMhz: number;
  highMhz: number;
  digitalRecorders: number;
  firstMatchCalls: number;
  coverableCalls: number;
  uniqueFrequencies: number;
  notes: string;
  isIssue: boolean;
};
export type TrSourcePlan = {
  systemShortName: string;
  lowMhz: number;
  highMhz: number;
  recommendedCenterMhz: number;
  assignedSourceIndex?: number | null;
  assignedDevice: string;
  notes: string;
  isIssue: boolean;
};
export type TrHealthSeries = { label: string; values: number[]; isBaseline: boolean };
export type TrHealthChart = { title: string; yAxisLabel: string; valueFormat: string; labels: string[]; series: TrHealthSeries[]; baselineNote: string };
export type TrHealthSummary = {
  title: string;
  window: string;
  lastWindow: string;
  source: string;
  summaryText: string;
  metrics: TrHealthMetric[];
  systems: TrHealthMetric[];
  sourceCoverage: TrSourceCoverage[];
  sourcePlan: TrSourcePlan[];
  remedies: TrHealthMetric[];
  charts: TrHealthChart[];
  samples: TrHealth[];
};
export type TrRfAnalysis = {
  system: string;
  start: number;
  end: number;
  window: string;
  hasEnoughPostChangeData: boolean;
  summary: string;
  metrics: TrHealthMetric[];
  comparison: TrHealthMetric[];
  retuneTargets: TrHealthMetric[];
  recommendations: TrHealthMetric[];
};
export type QualityAuditGroup = {
  label: string;
  totalCalls: number;
  problemCalls: number;
  inaudibleCalls: number;
  problemPercent: number;
  inaudiblePercent: number;
};
export type QualityAuditHour = { hour: number; totalCalls: number; problemCalls: number; inaudibleCalls: number };
export type QualityAuditSample = {
  callId: number;
  startTime: number;
  systemShortName: string;
  source: number;
  talkgroup: number;
  talkgroupName: string;
  category: string;
  durationSeconds: number;
  transcriptionStatus: string;
  qualityReason: string;
  transcription: string;
  audioUrl: string;
};
export type QualityAudit = {
  totalCalls: number;
  problemCalls: number;
  inaudibleCalls: number;
  problemPercent: number;
  inaudiblePercent: number;
  byReason: QualityAuditGroup[];
  bySystem: QualityAuditGroup[];
  byTalkgroup: QualityAuditGroup[];
  byHour: QualityAuditHour[];
  samples: QualityAuditSample[];
};
export type TrTroubleshoot = {
  health: TrHealthSummary;
  qualityAudit: QualityAudit;
  config: any;
  logOutput: string;
  diagnostics: string;
  insightsText: string;
};
export type TokenUsageSummary = { requests: number; successes: number; failures: number; promptTokens: number; completionTokens: number; totalTokens: number; estimatedStandardCost: number };
export type TokenUsageBucket = { label: string; totalTokens: number; promptTokens: number; completionTokens: number; requests: number };
export type TokenUsageEntry = { id: number; timestampUtc: string; triggerActivity: string; requestKind: string; success: boolean; error: string; endpoint: string; requestModel: string; responseModel: string; finishReason: string; inputChars: number; payloadChars: number; promptTokens: number; completionTokens: number; totalTokens: number };
export type TokenUsageReport = { ledger: string; summary: TokenUsageSummary; byDay: TokenUsageBucket[]; byTrigger: TokenUsageBucket[]; entries: TokenUsageEntry[] };
export type ProcessingProfile = { id: string; name: string; includePolice: boolean; includeFire: boolean; includeEMS: boolean; includeTraffic: boolean; includeOther: boolean; allowedTalkgroups: number[]; createdAtUtc?: string; updatedAtUtc?: string };
export type ProfileState = { activeProfileId: string; profiles: ProcessingProfile[] };
export type TalkgroupOption = { talkgroup: number; label: string; category: string };
export type TalkgroupCatalogItem = {
  id: number;
  mode: string;
  alphaTag: string;
  description: string;
  tag: string;
  sourceCategory: string;
  opsCategory: string;
  enabled: boolean;
  source: string;
  notes: string;
  updatedAtUtc?: string;
};
export type TalkgroupCatalogDocument = { schemaVersion: number; updatedAtUtc?: string; items: TalkgroupCatalogItem[] };
export type TalkgroupCatalogResponse = {
  catalogPath: string;
  generatedCsvPath: string;
  trRestartRecommended: boolean;
  warning: string;
  document: TalkgroupCatalogDocument;
};
export type TalkgroupCatalogSaveResult = { count: number; backupPath?: string | null; generatedCsvPath: string; generatedCsvBackupPath?: string | null; trRestartRecommended: boolean };
export type TalkgroupTrCsvResult = { path: string; backupPath?: string | null; enabledCount: number };
export type SetupCheck = { id: string; label: string; required: boolean; ok: boolean; message: string };
export type SetupStatus = {
  completed: boolean;
  currentStep: string;
  checks: SetupCheck[];
  detection: any;
  values: any;
};
export type SetupValidationResult = { ok: boolean; message: string; detail?: any };
export type SetupTalkgroupRow = { id: number; mode: string; alphaTag: string; description: string; tag: string; category: string; opsCategory: string; included: boolean; exclusionReason: string };
export type SetupTalkgroupPreview = { rows: SetupTalkgroupRow[]; includedByCategory: Record<string, number>; includedCount: number; excludedCount: number; diagnostics: string };
export type SetupTrConfigSystem = { systemName: string; shortName: string; siteName: string; frequenciesMhz: number[]; controlChannelsMhz: number[]; centerFrequency: number; assignedSerial: string; warning: string };
export type SetupTrConfigSource = { label: string; serial: string; centerFrequency: number; sampleRate: number; coveredFrequenciesMhz: number[]; omittedFrequenciesMhz: number[] };
export type SetupTrConfigDraft = { configJson: string; systems: SetupTrConfigSystem[]; sources: SetupTrConfigSource[]; warnings: string[]; diagnostics: string };
export type SetupCalibrationRange = { lowHz: number; highHz: number; centerHz: number };
export type SetupCalibrationSystemPlan = { shortName: string; modulation: string; controlChannelsHz: number[]; voiceFrequenciesHz: number[]; requiredRanges: SetupCalibrationRange[]; requiredSdrCount: number; proposedSourceIndexes: number[]; warnings: string[] };
export type SetupCalibrationSourcePlan = { index: number; serial: string; device: string; centerFrequency: number; sampleRate: number; errorHz: number; gain: string; coveredSystems: string[] };
export type SetupCalibrationPlan = { systems: SetupCalibrationSystemPlan[]; sources: SetupCalibrationSourcePlan[]; warnings: string[]; diagnostics: string };
